version: '3'
services:
  qb:
    build:
      context: .
      dockerfile: ./Dockerfile-gpu
    # image: "docker.io/entilzha/quizbowl-gpu:0.1"
    ports:
      - "4861:4861"
    volumes:
      - ./src/:/src
      - ./data/:/src/data
    devices:
      - /dev/nvidia0
      - /dev/nvidia-modeset
      - /dev/nvidia-uvm-tools
      - /dev/nvidiactl
      - /dev/nvidia-uvm
    command: ["bash", "run.sh"]
  eval:
    image: "docker.io/entilzha/quizbowl-gpu:0.1"
    volumes:
      - ./src/:/src
      - ./data/:/src/data
      - ./:/eval
    command: [
      "python", "/eval/evaluate.py",
      "--curve-pkl", "/eval/curve_pipeline.pkl",
      "--wait", "5",
      "--hostname", "qb",
      "--norun-web",
      "--char_step_size", "60",
#      "--retrieve_paragraphs", "False",
      "data/qanta.dev.json"
    ]
    depends_on:
      - "qb"
    environment:
      - "PYTHONUNBUFFERED=1"
